### ISSUE TITLE
Refinement suggestions

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/idc-pathomics-use-case-1#5]
I will keep a running list here, since most of those I anticipate will be minor and should be easy to address:
* we need to decide if this repo will stand on its own, or should be integrated into IDC-Examples; I would prefer the latter, but it's up to you André and Daniela (if we merge it, we should keep this repo with the forward pointer to prevent broken links, since I plan to mention this repo in the announcement today)
* would be good to add an option to run inference only, and download the trained network from some fixed location (I think the best place for this would be as an attachment under GitHub Releases - if the file is not too big - attachment cap is 2Gb)
* I woud add `%%capture` for the cells that do linux package installation - the output of those is probably of no value to the users, but can get quite long

**Comment by fedorov** [comment]
Download cell has been running for over 30 minutes now, and I downloaded just around 80 slides!

**Comment by DanielaSchacherer** [comment]
> Download cell has been running for over 30 minutes now, and I downloaded just around 80 slides!

Yes, I know. That is exactly what I referred to in one of my mails. The model training can be reduced to 30min easily, however generating the tiles (which requires at the moment downloading the WSI) can not. Thus, the possibility to query and download specific tiles from the IDC will be of great value I think :)

**Comment by DanielaSchacherer** [comment]
@fedorov Just to let you know: The prerequisites you added were a bit repetitive with what was written below in the customization section, so I merged these two. I hope it is fine. 
Also I messed it up a little with merging development and master branch, please just ignore the last commits. They are not meaningful :)

**Comment by fedorov** [comment]
Thanks. I just thought it is good to have those in the opening of the notebook.

**Comment by ahomeyer** [comment]
Should we consider the `SOPInstanceUIDs ` in order to demonstrate how to use IDC data versioning?

**Comment by fedorov** [comment]
> Should we consider the `SOPInstanceUIDs` in order to demonstrate how to use IDC data versioning?

@ahomeyer this is a bit tricky! `SOPInstanceUID` uniquely identifies DICOM instance within a version, but if that instance is changed in the next version, `SOPInstanceUID` may or may not change. To properly demonstrate versioning I think we would need to use [CRDC GUIDs](https://learn.canceridc.dev/data/organization-of-data/guids-and-uuids), or `SOPInstanceUID`s + IDC data version. Unfortunately, IDC data version right now is not included in the cohort manifest other than in the header, but we do plan to address this better - see this open issue: https://github.com/ImagingDataCommons/IDC-WebApp/issues/738.

**Comment by DanielaSchacherer** [comment]
Can be closed since notebooks are open-source already.
